export const Events = {
  Dom: 'DOMContentLoaded',
  Load: 'load',
  Resize: 'resize',
  Scroll: 'scroll',
  Click: 'click',
  Wheel: 'wheel',
  Change: 'change',
  ToStart: 'touchstart',
  ToEnd: 'touchend',
  ToMove: 'touchmove',
  MoEnter: 'mouseenter',
  MoLeave: 'mouseleave',
  MoMove: 'mousemove',
  TransStart: 'transitionstart',
  TransEnd: 'transitionend',
  Keydown: 'keydown',
  Keyup: 'keyup',
} as const;
